export type Product = {
  id: number;
  name: string;
  category: string;
  imageId: string;
  price: number;
  originalPrice?: number;
  features: string[];
  description?: string;
  available?: boolean;
};

export const products: Product[] = [
  {
    id: 1,
    name: "MARIE'BLACHERE",
    category: 'Negocios',
    imageId: 'img-marie',
    price: 0.00,
    features: ['QBCore & ESX Compatible', 'Plug & Play', 'Support'],
    description: "Panaderia pequeña, donde pararte a comprar un buen bocadillo o una barra de pan.\n\n📍 Ubicación: Grove Street\n👥 Trabajadores: Min 3 / Max 8\n🥐 Servicios y productos: Bollería, bocadillos fríos y calientes, comida para llevar.",
    available: true,
  },
  {
    id: 18,
    name: 'PEARLS',
    category: 'Negocios',
    imageId: 'img-vanilla',
    price: 0.00,
    features: ['Ambiente nocturno', 'Música en vivo', 'Exclusivo'],
    description: "La joya de la corona de la vida nocturna. Pearls redefine la exclusividad con un ambiente refinado, coctelería de clase mundial y los eventos más cotizados de la ciudad.\n\n📍 Ubicación: Vespucci Beach\n👥 Trabajadores: Min 4 / Max 12\n🥐 Servicios y productos: Reservados VIP, coctelería premium, seguridad privada y la mejor atmósfera de la costa.",
    available: true,
  },
  {
    id: 3,
    name: "BENNY'S",
    category: 'Negocios',
    imageId: 'img-bennys',
    price: 0.00,
    features: ['QBCore & ESX Compatible', 'Plug & Play', 'Support'],
    description: "Taller mecánico especializado en modificaciones de alto rendimiento.\n\n📍 Ubicación: Strawberry\n👥 Trabajadores: Min 5 / Max 15\n🥐 Servicios y productos: Tuning motor, estética avanzada y reparaciones.",
    available: false,
  },
  {
    id: 4,
    name: 'BEAN MACHINE',
    category: 'Negocios',
    imageId: 'img-bean',
    price: 0.00,
    features: ['QBCore & ESX Compatible', 'Plug & Play', 'Support'],
    description: "Cafetería icónica de Los Santos, el lugar perfecto para un café rápido y un donut.\n\n📍 Ubicación: Mission Row\n👥 Trabajadores: Min 2 / Max 6\n🥐 Servicios y productos: Café, donuts, bollería y snacks.",
    available: true,
  },
  {
    id: 8,
    name: 'UpnAtom',
    category: 'Negocios',
    imageId: 'img-upnatom',
    price: 0.00,
    features: ['Exclusividad', 'Eventos VIP', 'Plug & Play'],
    description: "Restaurante de comida rápida con temática atómica, el lugar ideal para una hamburguesa rápida y deliciosa.\n\n📍 Ubicación: Del Perro Pier\n👥 Trabajadores: Min 3 / Max 10\n🥐 Servicios y productos: Hamburguesas, batidos, patatas fritas y servicio rápido.",
    available: true,
  },
  {
    id: 9,
    name: 'BURGERSHOT',
    category: 'Negocios',
    imageId: 'img-burgershot',
    price: 0.00,
    features: ['Cocina rápida', 'Menú icónico', 'Gestión de stock'],
    description: "Restaurante de comida rápida especializado en las mejores hamburguesas de la ciudad.\n\n📍 Ubicación: Vespucci Canals\n👥 Trabajadores: Min 2 / Max 8\n🥐 Servicios y productos: Hamburguesas, patatas, bebidas y helados.",
    available: true,
  },
  {
    id: 11,
    name: 'FRUIT MACHINE',
    category: 'Negocios',
    imageId: 'img-fruit',
    price: 0.00,
    features: ['Zumos naturales', 'Batidos', 'Vida sana'],
    description: "Tu parada ideal para disfrutar de los mejores zumos y batidos naturales de Los Santos.\n\n📍 Ubicación: Vespucci Beach\n👥 Trabajadores: Min 2 / Max 6\n🥐 Servicios y productos: Batidos de frutas, bowls de açai y snacks saludables.",
    available: true,
  },
  {
    id: 12,
    name: 'LA FITNESS',
    category: 'Negocios',
    imageId: 'img-fitness',
    price: 0.00,
    features: ['Entrenamiento', 'Nutrición', 'Maquinaria'],
    description: "Centro deportivo de alto rendimiento equipado con la mejor tecnología para tu entrenamiento físico.\n\n📍 Ubicación: Legion Square\n👥 Trabajadores: Min 4 / Max 12\n🥐 Servicios y productos: Membresías, batidos de proteínas y planes de entrenamiento.",
    available: true,
  },
  {
    id: 13,
    name: 'CORRETTO',
    category: 'Negocios',
    imageId: 'img-showroom',
    price: 0.00,
    features: ['Café de Autor', 'Pastelería Italiana', 'Plug & Play'],
    description: "La auténtica experiencia del espresso italiano llega a la ciudad. Un rincón exclusivo donde el aroma del grano recién molido y la elegancia se fusionan para los paladares más refinados.\n\n📍 Ubicación: Rockford Hills\n👥 Trabajadores: Min 2 / Max 5\n🥐 Servicios y productos: Café premium, repostería artesanal italiana, paninis gourmet y el mejor ambiente de la zona.",
    available: false,
  },
  {
    id: 2,
    name: 'NOTWEN ALL SCRIPTS (40% OFF)',
    category: 'Packs',
    imageId: 'img-city',
    price: 747.78,
    originalPrice: 1246.30,
    features: ['QBCore & ESX Compatible', 'Plug & Play', 'Support'],
    description: "El paquete definitivo que incluye todos nuestros activos con un descuento masivo.",
    available: false,
  },
  {
    id: 5,
    name: 'POSTULACIÓN STAFF',
    category: 'Postulacion',
    imageId: 'img-staff',
    price: 0.00,
    features: ['Formación incluida', 'Comunidad activa', 'Ascensos'],
    description: 'Buscamos personas comprometidas para ayudar a nuestra comunidad en el día a día.',
    available: true,
  },
  {
    id: 6,
    name: 'POSTULACIÓN LSPD',
    category: 'Postulacion',
    imageId: 'img-lspd',
    price: 0.00,
    features: ['Gestión de equipo', 'Rol serio', 'Responsabilidad'],
    description: '¿Tienes experiencia liderando cuerpos policiales? Únete al departamento de policía.',
    available: true,
  },
  {
    id: 15,
    name: 'POSTULACIÓN EMS',
    category: 'Postulacion',
    imageId: 'img-ems',
    price: 0.00,
    features: ['Servicio médico', 'Rescate', 'Compromiso'],
    description: 'Buscamos médicos y enfermeros dedicados para salvar vidas en Los Santos.',
    available: true,
  },
  {
    id: 17,
    name: 'POSTULACIÓN MECÁNICOS',
    category: 'Postulacion',
    imageId: 'img-mechanic',
    price: 0.00,
    features: ['Reparaciones', 'Modificaciones', 'Tuning'],
    description: 'Forma parte de nuestro equipo de taller y demuestra tus habilidades mecánicas.',
    available: true,
  },
  {
    id: 7,
    name: 'VIP BRONCE',
    category: 'VIP',
    imageId: 'img-vip-bronce',
    price: 15.00,
    features: ['Acceso prioritario', 'Ropa exclusiva', 'Discord Role'],
    description: 'Nivel básico de membresía VIP con beneficios esenciales.',
    available: false,
  },
];
