
export type Product = {
  id: number;
  name: string;
  category: string;
  imageId: string;
  price: number;
  originalPrice?: number;
  features: string[];
  description?: string;
  available?: boolean;
};

export const products: Product[] = [
  {
    id: 1,
    name: "MARIE'BLACHERE",
    category: 'Negocios',
    imageId: 'img-marie',
    price: 0.00,
    features: ['QBCore & ESX Compatible', 'Plug & Play', 'Support'],
    description: "Panaderia pequeña, donde pararte a comprar un buen bocadillo o una barra de pan.\n\n📍 Ubicación: Grove Street\n👥 Trabajadores: Min 3 / Max 8\n🥐 Servicios y productos: Bollería, bocadillos fríos y calientes, comida para llevar.",
    available: true,
  },
  {
    id: 3,
    name: "BENNY'S",
    category: 'Negocios',
    imageId: 'img-bennys',
    price: 0.00,
    features: ['QBCore & ESX Compatible', 'Plug & Play', 'Support'],
    description: "Taller mecánico especializado en modificaciones de alto rendimiento.\n\n📍 Ubicación: Strawberry\n👥 Trabajadores: Min 5 / Max 15\n🥐 Servicios y productos: Tuning motor, estética avanzada y reparaciones.",
    available: false,
  },
  {
    id: 4,
    name: 'BEAN MACHINE',
    category: 'Negocios',
    imageId: 'img-bean',
    price: 0.00,
    features: ['QBCore & ESX Compatible', 'Plug & Play', 'Support'],
    description: "Cafetería icónica de Los Santos, el lugar perfecto para un café rápido y un donut.\n\n📍 Ubicación: Mission Row\n👥 Trabajadores: Min 2 / Max 6\n🥐 Servicios y productos: Café, donuts, bollería y snacks.",
    available: true,
  },
  {
    id: 8,
    name: 'UpnAtom',
    category: 'Negocios',
    imageId: 'img-upnatom',
    price: 0.00,
    features: ['Exclusividad', 'Eventos VIP', 'Plug & Play'],
    description: "Restaurante de comida rápida con temática atómica, el lugar ideal para una hamburguesa rápida y deliciosa.\n\n📍 Ubicación: Del Perro Pier\n👥 Trabajadores: Min 3 / Max 10\n🥐 Servicios y productos: Hamburguesas, batidos, patatas fritas y servicio rápido.",
    available: true,
  },
  {
    id: 9,
    name: 'BURGERSHOT',
    category: 'Negocios',
    imageId: 'img-burgershot',
    price: 0.00,
    features: ['Cocina rápida', 'Menú icónico', 'Gestión de stock'],
    description: "Restaurante de comida rápida especializado en las mejores hamburguesas de la ciudad.\n\n📍 Ubicación: Vespucci Canals\n👥 Trabajadores: Min 2 / Max 8\n🥐 Servicios y productos: Hamburguesas, patatas, bebidas y helados.",
    available: true,
  },
  {
    id: 11,
    name: 'FRUIT MACHINE',
    category: 'Negocios',
    imageId: 'img-fruit',
    price: 0.00,
    features: ['Zumos naturales', 'Batidos', 'Vida sana'],
    description: "Tu parada ideal para disfrutar de los mejores zumos y batidos naturales de Los Santos.\n\n📍 Ubicación: Vespucci Beach\n👥 Trabajadores: Min 2 / Max 6\n🥐 Servicios y productos: Batidos de frutas, bowls de açai y snacks saludables.",
    available: true,
  },
  {
    id: 12,
    name: 'LA FITNESS',
    category: 'Negocios',
    imageId: 'img-fitness',
    price: 0.00,
    features: ['Entrenamiento', 'Nutrición', 'Maquinaria'],
    description: "Centro deportivo de alto rendimiento equipado con la mejor tecnología para tu entrenamiento físico.\n\n📍 Ubicación: Legion Square\n👥 Trabajadores: Min 4 / Max 12\n🥐 Servicios y productos: Membresías, batidos de proteínas y planes de entrenamiento.",
    available: true,
  },
  {
    id: 13,
    name: 'PREMIUM SHOWROOM',
    category: 'Negocios',
    imageId: 'img-showroom',
    price: 0.00,
    features: ['Exposición de lujo', 'Venta de vehículos', 'Plug & Play'],
    description: "El concesionario más exclusivo de la ciudad para los ciudadanos más exigentes.\n\n📍 Ubicación: Rockford Hills\n👥 Trabajadores: Min 2 / Max 5\n🥐 Servicios y productos: Vehículos de alta gama, financiación y seguros.",
    available: true,
  },
  {
    id: 14,
    name: 'LTD GAS STATION',
    category: 'Negocios',
    imageId: 'img-ltd',
    price: 0.00,
    features: ['Suministro 24/7', 'Tienda de conveniencia', 'Plug & Play'],
    description: "Estación de servicio completa con tienda de snacks y suministros para tu vehículo.\n\n📍 Ubicación: Little Seoul\n👥 Trabajadores: Min 1 / Max 4\n🥐 Servicios y productos: Gasolina, comida rápida, reparación básica y café.",
    available: true,
  },
  {
    id: 2,
    name: 'NOTWEN ALL SCRIPTS (40% OFF)',
    category: 'Packs',
    imageId: 'img-city',
    price: 747.78,
    originalPrice: 1246.30,
    features: ['QBCore & ESX Compatible', 'Plug & Play', 'Support'],
    description: "El paquete definitivo que incluye todos nuestros activos con un descuento masivo.",
    available: false,
  },
  {
    id: 5,
    name: 'POSTULACIÓN STAFF',
    category: 'Postulacion',
    imageId: 'img-staff',
    price: 0.00,
    features: ['Formación incluida', 'Comunidad activa', 'Ascensos'],
    description: 'Buscamos personas comprometidas para ayudar a nuestra comunidad en el día a día.',
    available: true,
  },
  {
    id: 6,
    name: 'LSPD',
    category: 'Postulacion',
    imageId: 'img-lspd',
    price: 0.00,
    features: ['Gestión de equipo', 'Rol serio', 'Responsabilidad'],
    description: '¿Tienes experiencia liderando cuerpos policiales? Esta es tu oportunidad.',
    available: true,
  },
  {
    id: 7,
    name: 'VIP BRONCE',
    category: 'VIP',
    imageId: 'img-city',
    price: 15.00,
    features: ['Acceso prioritario', 'Ropa exclusiva', 'Discord Role'],
    description: 'Nivel básico de membresía VIP con beneficios esenciales.',
    available: false,
  },
];
